theme = "catppuccin_macchiato_transparent"
#######
[editor]
shell = ["fish", "-c"]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
completion-trigger-len = 5
preview-completion-insert = false
auto-completion = false
idle-timeout = 250
bufferline = "multiple"
popup-border = "popup"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "separator", "total-line-numbers", "separator", "spacer", "version-control"]
right = ["register", "spacer", "diagnostics", "separator", "selections", "separator", "position", "position-percentage", "spacer", "separator", "file-encoding", "file-line-ending", "separator", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line="warning"

# [editor.file-picker]
# max-depth = 10

[editor.soft-wrap]
enable = true

[keys.normal]
backspace = { w = ":w", S-w = ":wa", A-S-w = ":wqa", d = ":bc", S-d = ":bca", q = ":q", S-q = ":qa!", A-q = ":q!", A-d = ":bc!", A-S-d = ":bca!" }
S-l = ":bn"
S-h = ":bp"
A-w = ":w"
A-z = "extend_line_above"

[keys.insert]
A-h = "move_char_left"
A-l = "move_char_right"
A-j = "move_line_down"
A-k = "move_line_up"


[keys.normal."+"]
r = ":run-shell-command cargo run"
b = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
